### PR TITLE
Add ability to sync dashboard state with URL parameters

### PR DESCRIPTION
**Pull request by philippjfr**
Adds a global `sync_query` config option and options on individual components.

- [x] Add (more) tests
- [x] Add documentation
- [ ] Add example

### CODE REVIEW

**Comment by philippjfr** [comment]
@maximlt What do you think about the naming of `sync_query`? Any better suggestions?

**Comment by maximlt** [comment]
I think it wouldn't hurt too much to add `url` somewhere in the name, to make it clear what the query is about. People may think it's about data querying for instance. Maybe `sync_url_query`?

**Comment by philippjfr** [comment]
Agreed, was also thinking about `sync_with_url`, which one is better?

**Comment by maximlt** [comment]
`sync_with_url`, definitely!

**Pull request merged**
