### PR TITLE
create how to add title

### PR DESCRIPTION
**Pull request by droumis**
completes doc task from #430

image

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for this but I think this is getting a little to granular. We can't add a how-to guide for every single parameter.

**Comment by droumis** [comment]
That's fine. I was asked to add it to the docs so I assumed that more than docstring reference was needed.

**Comment by philippjfr** [comment]
I think we just need to work out what the appropriate scope for a how to section is. I could see this being part of a guide about laying out multiple views for example.

**Comment by droumis** [comment]
I'll close it for now. we can revisit later

**Pull request closed without merging**
